# Generated by Django 4.1.7 on 2023-05-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=20, null=True)),
                ('sub_id', models.CharField(max_length=20, null=True)),
                ('time', models.IntegerField(null=True)),
                ('energy_dict', models.TextField(null=True)),
                ('carbon_graph1', models.ImageField(null=True, upload_to='')),
                ('carbon_graph2', models.ImageField(null=True, upload_to='')),
                ('energy_graph1', models.ImageField(null=True, upload_to='')),
                ('energy_graph2', models.ImageField(null=True, upload_to='')),
                ('cost_graph1', models.ImageField(null=True, upload_to='')),
                ('cost_graph2', models.ImageField(null=True, upload_to='')),
                ('total_usage', models.FloatField(null=True)),
                ('usage_percentage', models.FloatField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='host',
            name='flexible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
