# Generated by Django 4.1.7 on 2023-05-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_rename_carbon_graph1_analysis_carbon_graph_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='analysis',
            old_name='cpu_usage',
            new_name='usage_percentage',
        ),
    ]
