# Generated by Django 4.1.7 on 2023-05-09 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_application_carbon_tariff_high_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysis',
            name='flex_carbon_graph',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='flex_cost_graph',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='analysis',
            name='flex_energy_dict',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='analysis',
            name='flex_energy_graph',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
