# Generated by Django 4.1.7 on 2023-05-09 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_delete_budget_remove_analysis_flex_carbon_graph_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='cost_footprint',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='cost_footprint_high',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='cost_footprint_low',
            field=models.FloatField(null=True),
        ),
    ]
