# Generated by Django 4.1.7 on 2023-05-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_host_carbon_saving_host_cost_saving'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='flexible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
