# Generated by Django 4.1.7 on 2023-04-22 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('current', models.CharField(max_length=25, null=True)),
                ('configured', models.IntegerField(default=0, null=True)),
                ('threshold_low', models.FloatField(default=15, max_length=25, null=True)),
                ('threshold_medium', models.FloatField(default=30, max_length=25, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailableDatacenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('datacenterid', models.CharField(max_length=20, null=True)),
                ('datacentername', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=20, null=True)),
                ('sub_id', models.CharField(max_length=20, null=True)),
                ('time', models.IntegerField(null=True)),
                ('energy_dict', models.TextField(null=True)),
                ('carbon_graph1', models.ImageField(null=True, upload_to='')),
                ('carbon_graph2', models.ImageField(null=True, upload_to='')),
                ('energy_graph1', models.ImageField(null=True, upload_to='')),
                ('energy_graph2', models.ImageField(null=True, upload_to='')),
                ('cost_graph1', models.ImageField(null=True, upload_to='')),
                ('cost_graph2', models.ImageField(null=True, upload_to='')),
                ('total_usage', models.FloatField(null=True)),
                ('usage_percentage', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguredDataCenters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('sub_id', models.CharField(max_length=15, null=True)),
                ('datacenterid', models.CharField(max_length=20)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField(null=True)),
                ('pue', models.FloatField()),
                ('energy_cost', models.FloatField()),
                ('carbon_conversion', models.FloatField()),
                ('budget', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('sub_id', models.CharField(max_length=15, null=True)),
                ('datacenterid', models.CharField(max_length=20, null=True)),
                ('floorid', models.IntegerField()),
                ('floorname', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('sub_id', models.CharField(max_length=15, null=True)),
                ('datacenterid', models.CharField(max_length=20, null=True)),
                ('floorid', models.IntegerField(null=True)),
                ('rackid', models.IntegerField()),
                ('hostid', models.IntegerField()),
                ('hostname', models.CharField(max_length=30)),
                ('hostdescription', models.CharField(max_length=50)),
                ('hostType', models.CharField(max_length=20)),
                ('processors', models.IntegerField()),
                ('ipaddress', models.CharField(max_length=25)),
                ('cpu_last_response', models.CharField(max_length=25, null=True)),
                ('cpu_usage', models.FloatField(null=True)),
                ('cpu_responses', models.IntegerField(null=True)),
                ('total_cpu', models.FloatField(null=True)),
                ('kWh_consumed', models.FloatField(null=True)),
                ('power_responses', models.IntegerField(null=True)),
                ('total_watt_hour', models.FloatField(null=True)),
                ('power_last_response', models.IntegerField(null=True)),
                ('TCO', models.FloatField(null=True)),
                ('carbon_footprint_3', models.FloatField(null=True)),
                ('ops_cons_3', models.FloatField(null=True)),
                ('op_cost_3', models.FloatField(null=True)),
                ('app_waste_cost_3', models.FloatField(null=True)),
                ('capital', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('masterip', models.CharField(max_length=25, null=True)),
                ('sub_id', models.CharField(max_length=15, null=True)),
                ('datacenterid', models.CharField(max_length=20, null=True)),
                ('floorid', models.IntegerField()),
                ('rackid', models.IntegerField()),
                ('rackname', models.CharField(max_length=25, null=True)),
                ('description', models.CharField(max_length=100, null=True)),
                ('pdu', models.IntegerField(null=True)),
            ],
        ),
    ]
