# Generated by Django 4.1.7 on 2023-05-06 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_host_flexible'),
    ]

    operations = [
        migrations.AlterField(
            model_name='host',
            name='flexible',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
