# Generated by Django 4.1.7 on 2023-05-09 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_rename_cpu_usage_analysis_usage_percentage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysis',
            name='usage_percentage',
        ),
        migrations.AddField(
            model_name='analysis',
            name='total_hours',
            field=models.FloatField(null=True),
        ),
    ]
