# Generated by Django 4.1.7 on 2023-05-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_remove_analysis_usage_percentage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='carbon_tariff_high',
            field=models.FloatField(default=1.2, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='carbon_tariff_low',
            field=models.FloatField(default=1, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cost_tariff_high',
            field=models.FloatField(default=1.2, max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='cost_tariff_low',
            field=models.FloatField(default=1, max_length=25, null=True),
        ),
    ]
