# Generated by Django 4.1.7 on 2023-05-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_host_cost_footprint_host_cost_footprint_high_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='host',
            old_name='cost_footprint',
            new_name='cost_energy',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='cost_footprint_high',
            new_name='cost_energy_high',
        ),
        migrations.RenameField(
            model_name='host',
            old_name='cost_footprint_low',
            new_name='cost_energy_low',
        ),
    ]
