# Generated by Django 4.1.7 on 2023-05-10 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_rename_cost_footprint_host_cost_energy_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='host',
            name='carbon_saving',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='host',
            name='cost_saving',
            field=models.FloatField(null=True),
        ),
    ]
